# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewBusSchedule' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewBusSchedule

  target 'NewBusScheduleTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Alamofire', '~> 4.4'
  end

  target 'NewBusScheduleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
